### PR TITLE
Jr contact page

### PR DESCRIPTION
**Pull request by elisa-arenas**
### Summary

This page allows for students to contact the correct SHPE Jr Officer based on their needs/wants.
After the user decides who to contact, they can click the **"Contact via email"** button which takes them directly to their email as shown below.

Picture of the button functionality:
contactUsFunctionality

### Reference

[Asana link](https://app.asana.com/0/1202843173947642/1204119918624938/f)

### Extra

@w-omar 
@IsabellaRC 
@j-jurado 
@victoriadealba

### CODE REVIEW

**Comment by w-omar** [comment]
Looks phenomenal, but there is a merge conflict in src/App.css
Please resolve these and it will be good for production. TX!

**Comment by elisa-arenas** [comment]
> Looks phenomenal, but there is a merge conflict in src/App.css Please resolve these and it will be good for production. TX!
 #182 
Just fixed merge conflictst #

**Comment by victoriadealba** [comment]
Screen Shot 2023-09-20 at 4 06 32 PM
I'd make 
the header only "Have questions about our SHPE JR Outreach and K-12 STEM Opportunities?" 

take out this: TO HAVE ELEMENTARY/MIDDLE SCHOOL STEM EVENTS, MENTORSHIPS, AND PROGRAM:
TO BECOME A PARTNERED HIGH SCHOOL CHAPTER: bc it's confusing to a user since the Shpejr chair helps with the process of becoming a partner school

**Comment by elisa-arenas** [comment]
> Screen Shot 2023-09-20 at 4 06 32 PM I'd make the header only "Have questions about our SHPE JR Outreach and K-12 STEM Opportunities?"
> take out this: TO HAVE ELEMENTARY/MIDDLE SCHOOL STEM EVENTS, MENTORSHIPS, AND PROGRAM: TO BECOME A PARTNERED HIGH SCHOOL CHAPTER: bc it's confusing to a user since the Shpejr chair helps with the process of becoming a partner school

Fixed!

**Comment by j-jurado** [comment]
Thanks for updating this! One more small thing: on mobile view, the text and card get smushed together. Is it possible to display the entire card in one column width with the text on top? 

Here's the current mobile view:
Screen Shot 2023-10-05 at 10 59 33 PM

Here's a reference:
Screen Shot 2023-10-05 at 10 59 12 PM

**Comment by elisa-arenas** [comment]
fixed the formatting and it should look like this now:

mobileForm

**Review by j-jurado — APPROVED** [review]
Thanks for addressing our comments, everything looks good to me.

**Pull request merged**
